import {EventEmitter} from '../utils/EventEmitter.js'
export const ScenePhase=Object.freeze({
UNINITIALIZED:0,
INITIALIZING:1,
READY:2,
ACTIVE:3,
PAUSED:4,
STOPPED:5,
DESTROYED:6
})
export class SceneState extends EventEmitter{
constructor(){
super()
this.phase=ScenePhase.UNINITIALIZED
this.previousPhase=null
this.sceneId=null
this.sceneName=null
this.loaded=false
this.active=false
this.visible=true
this.paused=false
this.destroyed=false
this.time=0
this.delta=0
this.frame=0
this.entities=0
this.components=0
this.systems=0
this.memoryUsage=0
this.gpuUsage=0
this.loadProgress=0
this.loadStartTime=0
this.loadEndTime=0
this.activationTime=0
this.deactivationTime=0
this.metadata=new Map()
this.flags={
initialized:false,
ready:false,
active:false,
paused:false,
visible:true
}
}
setPhase(phase){
if(this.phase===phase)return
this.previousPhase=this.phase
this.phase=phase
this.emit('phaseChanged',phase,this.previousPhase)
}
initialize(id,name){
this.sceneId=id
this.sceneName=name
this.flags.initialized=true
this.loadStartTime=performance.now()
this.setPhase(ScenePhase.INITIALIZING)
this.emit('initialize',id,name)
}
setLoadProgress(progress){
this.loadProgress=Math.max(0,Math.min(1,progress))
this.emit('loadProgress',this.loadProgress)
if(this.loadProgress===1){
this.loaded=true
this.loadEndTime=performance.now()
this.flags.ready=true
this.setPhase(ScenePhase.READY)
this.emit('ready',this.sceneId)
}
}
activate(){
if(!this.loaded)return
this.active=true
this.paused=false
this.flags.active=true
this.activationTime=performance.now()
this.setPhase(ScenePhase.ACTIVE)
this.emit('activated',this.sceneId)
}
pause(){
if(!this.active)return
this.paused=true
this.flags.paused=true
this.setPhase(ScenePhase.PAUSED)
this.emit('paused',this.sceneId)
}
resume(){
if(!this.paused)return
this.paused=false
this.flags.paused=false
this.setPhase(ScenePhase.ACTIVE)
this.emit('resumed',this.sceneId)
}
deactivate(){
if(!this.active)return
this.active=false
this.flags.active=false
this.deactivationTime=performance.now()
this.setPhase(ScenePhase.STOPPED)
this.emit('deactivated',this.sceneId)
}
setVisible(visible){
this.visible=visible
this.flags.visible=visible
this.emit('visibilityChanged',visible)
}
update(delta,time,frame){
if(!this.active||this.paused)return
this.delta=delta
this.time=time
this.frame=frame
this.emit('update',delta,time,frame)
}
setEntityCount(count){
this.entities=count
this.emit('entityCountChanged',count)
}
setComponentCount(count){
this.components=count
this.emit('componentCountChanged',count)
}
setSystemCount(count){
this.systems=count
this.emit('systemCountChanged',count)
}
setMemoryUsage(bytes){
this.memoryUsage=bytes
this.emit('memoryChanged',bytes)
}
setGPUUsage(bytes){
this.gpuUsage=bytes
this.emit('gpuChanged',bytes)
}
setMetadata(key,value){
this.metadata.set(key,value)
this.emit('metadataChanged',key,value)
}
getMetadata(key){
return this.metadata.get(key)
}
removeMetadata(key){
if(this.metadata.has(key)){
this.metadata.delete(key)
this.emit('metadataRemoved',key)
}
}
clearMetadata(){
this.metadata.clear()
this.emit('metadataCleared')
}
reset(){
this.time=0
this.delta=0
this.frame=0
this.entities=0
this.components=0
this.systems=0
this.memoryUsage=0
this.gpuUsage=0
this.loadProgress=0
this.flags.ready=false
this.flags.active=false
this.flags.paused=false
this.setPhase(ScenePhase.UNINITIALIZED)
this.emit('reset')
}
destroy(){
if(this.destroyed)return
this.destroyed=true
this.deactivate()
this.setPhase(ScenePhase.DESTROYED)
this.removeAllListeners()
}
isReady(){
return this.phase===ScenePhase.READY||this.phase===ScenePhase.ACTIVE
}
isActive(){
return this.phase===ScenePhase.ACTIVE
}
isPaused(){
return this.phase===ScenePhase.PAUSED
}
isDestroyed(){
return this.phase===ScenePhase.DESTROYED
}
}
